In [61]:
import numpy as np
import pandas as pd
import Constants
import os

In [62]:
df = pd.read_excel(os.path.join(Constants.ROOT_DIR,'data','movies.xlsx'))

In [48]:
df

Film  Year          Script Type  \
0                                300  2007           adaptation   
1                       3:10 to Yuma  2007               remake   
2                   30 Days of Night  2007           adaptation   
3                Across the Universe  2007  original screenplay   
4       Alien vs. Predator - Requiem  2007               sequel   
...                              ...   ...                  ...   
1397                       Wish Upon  2017  original screenplay   
1398                          Wonder  2017           adaptation   
1399                    Wonder Woman  2017           adaptation   
1400  xXx: The Return of Xander Cage  2017               sequel   
1401                      Your Name.  2017           adaptation   

     Rotten Tomatoes  critics Metacritic  critics Average critics   \
0                          60                  51               56   
1                          88                  76               82   
2                          50                  53               52   
3                          54                  56               55   
4                          14                  29               22   
...                       ...                 ...              ...   
1397                       17                  32               25   
1398                       85                  66               76   
1399                       92                  76               84   
1400                       45                  42               44   
1401                       97                  79               88   

      Rotten Tomatoes Audience  Metacritic Audience   \
0                          89.0                   71   
1                          86.0                   73   
2                          56.0                   65   
3                          82.0                   73   
4                          31.0                   45   
...                         ...                  ...   
1397                       32.0                   40   
1398                       91.0                   77   
1399                       89.0                   78   
1400                       38.0                   48   
1401                       94.0                   90   

     Rotten Tomatoes vs Metacritic  deviance Average audience   ...  \
0                                         18                80  ...   
1                                         13                80  ...   
2                                         -9                61  ...   
3                                          9                78  ...   
4                                        -14                38  ...   
...                                      ...               ...  ...   
1397                                      -8                36  ...   
1398                                      14                84  ...   
1399                                      11                84  ...   
1400                                     -10                43  ...   
1401                                       4                92  ...   

      of Gross earned abroad Budget ($million)  Budget recovered  \
0                     53.82%                65           701.64%   
1                     23.18%                50           139.56%   
2                     47.31%                32           234.67%   
3                     17.11%                45            65.26%   
4                     67.57%                40           322.21%   
...                      ...               ...               ...   
1397                   0.00%                12           119.18%   
1398                  22.16%                20           661.80%   
1399                  49.80%               149           551.52%   
1400                  87.03%                85           407.23%   
1401                  98.59%                 -                 -   

      Budget recovered opening weekend  Dis

In [4]:
print(df.columns)

Index(['Film', 'Year', 'Script Type', 'Rotten Tomatoes  critics',
       'Metacritic  critics', 'Average critics ', 'Rotten Tomatoes Audience ',
       'Metacritic Audience ', 'Rotten Tomatoes vs Metacritic  deviance',
       'Average audience ', 'Audience vs Critics deviance ', 'Primary Genre',
       'Genre', 'Opening Weekend', 'Opening weekend ($million)',
       'Domestic Gross', 'Domestic gross ($million)',
       'Foreign Gross ($million)', 'Foreign Gross', 'Worldwide Gross',
       'Worldwide Gross ($million)', ' of Gross earned abroad',
       'Budget ($million)', ' Budget recovered',
       ' Budget recovered opening weekend', 'Distributor', 'IMDb Rating',
       'IMDB vs RT disparity', 'Release Date (US)', 'Oscar Winners',
       'Oscar Detail'],
      dtype='object')


In [17]:
df.dtypes

Film                                        object
Year                                         int64
Script Type                                 object
Rotten Tomatoes  critics                    object
Metacritic  critics                         object
Average critics                             object
Rotten Tomatoes Audience                   float64
Metacritic Audience                         object
Rotten Tomatoes vs Metacritic  deviance     object
Average audience                            object
Audience vs Critics deviance                object
Primary Genre                               object
Genre                                       object
Opening Weekend                             object
Opening weekend ($million)                 float64
Domestic Gross                              object
Domestic gross ($million)                  float64
Foreign Gross ($million)                    object
Foreign Gross                               object
Worldwide Gross                

In [71]:
df.groupby('Oscar Winners').count()['Film']

Oscar Winners
False    1346
True       56
Name: Film, dtype: int64

In [64]:
df['Oscar Winners'].unique()

array([nan, 'Oscar winner', 'Oscar Winner'], dtype=object)

In [65]:
def clean_oscar_winners(x):
    if not pd.isna(x):
        if x == 'Oscar winner' or x == 'Oscar Winner':
            return True
    return False
    
df['Oscar Winners'] = df['Oscar Winners'].map(lambda x:clean_oscar_winners(x))
df['Oscar Winners'].unique()

array([False,  True])

In [66]:
percentage_of_not_nan=(df['Oscar Winners']== True).sum()/len(df) * 100
print(f"Percentage of `Oscar Winners` valid data: {percentage_of_not_nan:.4}%")

Percentage of `Oscar Winners` valid data: 3.994%


In [55]:
df['Oscar Detail'].unique()

array([nan, 'Best Original Screenplay', 'Best Supporting Actress',
       'Best Picture, Best Director, Best Supporting Actor, Best Adapted Screenplay',
       'Best Animated Feature', 'Best Art Direction',
       'Best Editing, Best Sound, Best Sound Editing',
       'Best Visual Effects', 'Best Actor, Best Cinematography',
       'Best Actor, Best Original Screenplay',
       'Best Picture, Best Director, Best Adapted Screenplay',
       'Best Actress',
       'Best Picture, Best Director, Best Original Screenplay',
       'Best Animated Film', 'Best Adapted Screenplay',
       'Best Picture, Best Director', 'Best Supporting Actor',
       'Best Director', 'Best Picture, Best Adapted Screenplay',
       'Best Original Screenplay (Spike Jonze)',
       'Best Actress (Cate Blanchett)',
       'Best Supporting Actor (Jared Leto), Best Makeup and Hairstyling (Adruitha Lee and Robin Mathews), Best Actor (Matthew McConaughey)',
       'Best Picture, Best Original Screenplay',
       'Best 

In [67]:
oscars = pd.read_csv(os.path.join(Constants.ROOT_DIR,'data','oscars.csv'))

In [68]:
oscars.sort_values(by='winners' ,inplace=True)
oscars

year           winners  \
1264  1987   'Round Midnight   
1885  2014  12 Years a Slave   
1892  2014  12 Years a Slave   
2037  2020              1917   
2045  2020              1917   
...    ...               ...   
890   1970                 Z   
891   1970                 Z   
1980  2017          Zootopia   
760   1965   Zorba the Greek   
762   1965   Zorba the Greek   

                                               category  
1264                         Best Music, Original Score  
1885                    Best Motion Picture of the Year  
1892                   Best Writing, Adapted Screenplay  
2037                 Best Achievement in Cinematography  
2045                   Best Achievement in Sound Mixing  
...                                                 ...  
890                                   Best Film Editing  
891                          Best Foreign Language Film  
1980             Best Animated Feature Film of the Year  
760   Best Art Direction-Set Decoration, Black-and-W...  
762                Best Cinematography, Black-and-White  

[2100 rows x 3 columns]

In [69]:
for i, film in enumerate(df['Film']):
    if pd.isna(df.loc[i,'Oscar Winners']):
        if film in oscars['winners'].values:
            df.loc[i,'Oscar Winners'] = True
            df.loc[i,'Oscar Detail'] = oscars[oscars['winners'] == film]['category'].iloc[0]


In [72]:
percentage_of_not_nan=(df['Oscar Winners']== True).sum()/len(df) * 100
print(f"Percentage of `Oscar Winners` valid data: {percentage_of_not_nan:.4}%")
# Gemisan ta dedomena kata +2.497%
df.groupby('Oscar Winners').count()['Film']

Percentage of `Oscar Winners` valid data: 3.994%


Oscar Winners
False    1346
True       56
Name: Film, dtype: int64

array([nan, 'Oscar Winner'], dtype=object)